### ISSUE TITLE
Feature: GraphQL Implementation

### ISSUE THREAD

**Issue by BosEriko** [kuru-studio/kuru-studio-social-server#10]
# Epic Title

Feature: GraphQL Implementation

## Epic Description

This Feature will add GraphQL fully to the server.

## List of Tasks (Complete in order)

1. [x] [Task: GraphQL Authentication](https://github.com/kuru-studio/kuru-studio-social-server/issues/11)
2. [x] [Task: GraphQL Connecting Nodes](https://github.com/kuru-studio/kuru-studio-social-server/issues/13)
3. [x] [Task: GraphQL Error Handling](https://github.com/kuru-studio/kuru-studio-social-server/issues/14)
4. [x] [Task: GraphQL Filtering](https://github.com/kuru-studio/kuru-studio-social-server/issues/15)
5. [x] [Task: GraphQL Pagination](https://github.com/kuru-studio/kuru-studio-social-server/issues/16)
